

[build]
  base = "frontend"
  publish = "build"
  command = "CI='' npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
